services:
  postgres:
    image: postgres:15
    container_name: pg-url-shortener
    restart: always
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
